export const CREATE_SESSION_BEGIN   = 'CREATE_SESSION_BEGIN';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAILURE = 'CREATE_SESSION_FAILURE';
export const RECOVER_PASSWORD_BEGIN = 'RECOVER_PASSWORD_BEGIN';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export const RECOVER_PASSWORD_FAILURE = 'RECOVER_PASSWORD_FAILURE';
